name: md_bootstrap
version: 1.0.1
description: AngularDart Bootstrap with Material Design
authors:
  - TLM source@legionmarket.com
homepage: https://github.com/Dart-Land/md_bootstrap
environment:
  sdk: '>=2.1.0-dev <3.0.0'
dependencies:
  angular: ^5.1.0
  js_shims: ^1.0.0
  intl: ^0.15.0
  bootstrap_sass: ^4.1.3+0
  stream_transform: ^0.0.11
  font_awesome: ^4.7.0
  angular_forms: ^2.0.0
dev_dependencies:
  build_runner: any
  sass_builder: ^2.1.1
