name: md_bootstrap
version: 1.0.1
description: AngularDart Bootstrap with Material Design
authors:
  - TLM source@legionmarket.com
homepage: https://github.com/Dart-Land/md_bootstrap
environment:
  sdk: '>=2.1.0-dev <3.0.0'
dependencies:
  angular: ^5.1.0
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha+20
  angular_components: ^0.10.1
  js_shims: ^1.0.0
  intl: ^0.15.0
  md_bootstrap_scss:
    git: https://github.com/Dart-Land/md_bootstrap_scss.git
  stream_transform: ^0.0.14+1
  font_awesome: 4.7.0+1
dev_dependencies:
  analyzer: ^0.33.0
  test: ^1.5.1
  angular_test: ^2.1.0
  build_test: ^0.10.3+3
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.4+2
  sass_builder: ^2.1.2
